{"name": "Создание заказа без авторизации", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался статус 401, но получен 200. Текст: {\"success\":true,\"name\":\"Фалленианский антарианский краторный бургер\",\"order\":{\"number\":9705}}\nassert 200 == 401\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_create_order.TestApiCreateOrderPost object at 0x10e403890>\nfixture_creating_order_without_authorization = {'ingredients': ['61c0c5a71d1f82001bdaaa6c', '61c0c5a71d1f82001bdaaa77', '61c0c5a71d1f82001bdaaa75']}\n\n    @allure.title(\"Создание заказа без авторизации\")\n    def test_creating_order_without_authorization(self, fixture_creating_order_without_authorization):\n        order = fixture_creating_order_without_authorization\n    \n    \n        with allure.step(\"Создаем заказ\"):\n            response = requests.post(api_orders_url, json=order)\n    \n            allure.attach(f\"Response: {response.text}\")\n    \n        with allure.step(\"Проверяем код ответа\"):\n>           assert response.status_code == 401, f\"Ожидался статус 401, но получен {response.status_code}. Текст: {response.text}\"\nE           AssertionError: Ожидался статус 401, но получен 200. Текст: {\"success\":true,\"name\":\"Фалленианский антарианский краторный бургер\",\"order\":{\"number\":9705}}\nE           assert 200 == 401\nE            +  where 200 = <Response [200]>.status_code\n\ntests/test_create_order.py:50: AssertionError"}, "steps": [{"name": "Создаем заказ", "status": "passed", "attachments": [{"source": "49da9cd2-ac06-45de-b3f3-21a3f067dd20-attachment.attach"}], "start": 1744476068616, "stop": 1744476068714}, {"name": "Проверяем код ответа", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался статус 401, но получен 200. Текст: {\"success\":true,\"name\":\"Фалленианский антарианский краторный бургер\",\"order\":{\"number\":9705}}\nassert 200 == 401\n +  where 200 = <Response [200]>.status_code\n", "trace": "  File \"/Users/misolka/Downloads/Diplom/Diplom_2 /tests/test_create_order.py\", line 50, in test_creating_order_without_authorization\n    assert response.status_code == 401, f\"Ожидался статус 401, но получен {response.status_code}. Текст: {response.text}\"\n"}, "start": 1744476068714, "stop": 1744476068715}], "start": 1744476068616, "stop": 1744476068717, "uuid": "c27988b6-fcf9-43fc-a228-a56c3e679616", "historyId": "34266f476e8599dc5e0ccf6df94601e7", "testCaseId": "34266f476e8599dc5e0ccf6df94601e7", "fullName": "tests.test_create_order.TestApiCreateOrderPost#test_creating_order_without_authorization", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestApiCreateOrderPost"}, {"name": "host", "value": "MacBook-Air-Alina.local"}, {"name": "thread", "value": "12998-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}